// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM3wL1YyNwKTNepLp7cqs1MCF2VXfOvOI',
    appId: '1:263901926070:ios:68778b6fa4bcbbc9134c17',
    messagingSenderId: '263901926070',
    projectId: 'socialappflutter-cca15',
    storageBucket: 'socialappflutter-cca15.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwmX9p_S6l5rXM4kVFjX6WajFTnhKMKlM',
    appId: '1:263901926070:web:487496d0d0daaf5c134c17',
    messagingSenderId: '263901926070',
    projectId: 'socialappflutter-cca15',
    authDomain: 'socialappflutter-cca15.firebaseapp.com',
    storageBucket: 'socialappflutter-cca15.firebasestorage.app',
    measurementId: 'G-YSY7SCW43N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmX9p_S6l5rXM4kVFjX6WajFTnhKMKlM',
    appId: '1:263901926070:web:487496d0d0daaf5c134c17',
    messagingSenderId: '263901926070',
    projectId: 'socialappflutter-cca15',
    authDomain: 'socialappflutter-cca15.firebaseapp.com',
    storageBucket: 'socialappflutter-cca15.firebasestorage.app',
    measurementId: 'G-YSY7SCW43N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM3wL1YyNwKTNepLp7cqs1MCF2VXfOvOI',
    appId: '1:263901926070:ios:68778b6fa4bcbbc9134c17',
    messagingSenderId: '263901926070',
    projectId: 'socialappflutter-cca15',
    storageBucket: 'socialappflutter-cca15.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Tq3Wom9O2xSpefTlHoD4IQziqXYKLC4',
    appId: '1:263901926070:android:35f8110aba26eb0a134c17',
    messagingSenderId: '263901926070',
    projectId: 'socialappflutter-cca15',
    storageBucket: 'socialappflutter-cca15.firebasestorage.app',
  );

}